export const AUDIT_ACTIONS = {
  // Authentication
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE: 'PASSWORD_RESET_COMPLETE',

  // User Management
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',

  // Role Management
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REMOVED: 'ROLE_REMOVED',
  ADMIN_ROLE_ASSIGNED: 'ADMIN_ROLE_ASSIGNED',
  ADMIN_ROLE_REMOVED: 'ADMIN_ROLE_REMOVED',

  // Data Operations
  DATA_CREATED: 'DATA_CREATED',
  DATA_UPDATED: 'DATA_UPDATED',
  DATA_DELETED: 'DATA_DELETED',
  BULK_DATA_OPERATION: 'BULK_DATA_OPERATION',

  // Claims Management
  CLAIM_CREATED: 'CLAIM_CREATED',
  CLAIM_UPDATED: 'CLAIM_UPDATED',
  CLAIM_DELETED: 'CLAIM_DELETED',
  CLAIM_STATUS_CHANGED: 'CLAIM_STATUS_CHANGED',

  // Policy Management
  POLICY_CREATED: 'POLICY_CREATED',
  POLICY_UPDATED: 'POLICY_UPDATED',
  POLICY_DELETED: 'POLICY_DELETED',

  // Payment Operations
  PAYMENT_PROCESSED: 'PAYMENT_PROCESSED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',

  // System Operations
  SYSTEM_CONFIG_CHANGED: 'SYSTEM_CONFIG_CHANGED',
  BACKUP_CREATED: 'BACKUP_CREATED',
  BACKUP_RESTORED: 'BACKUP_RESTORED',

  // Security Events
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  SECURITY_BREACH_ATTEMPT: 'SECURITY_BREACH_ATTEMPT',
  ACCESS_DENIED: 'ACCESS_DENIED',

  // Admin Surface
  ADMIN_DASHBOARD_VIEW: 'ADMIN_DASHBOARD_VIEW',
  ADMIN_ACTIVE_USERS_VIEW: 'ADMIN_ACTIVE_USERS_VIEW',
  ADMIN_GAMES_SUMMARY_VIEW: 'ADMIN_GAMES_SUMMARY_VIEW',
  ADMIN_SYSTEM_HEALTH_VIEW: 'ADMIN_SYSTEM_HEALTH_VIEW',
  ADMIN_EXPORT_CSV: 'ADMIN_EXPORT_CSV',
  ADMIN_BADGE_CREATED: 'ADMIN_BADGE_CREATED',
  ADMIN_BADGE_UPDATED: 'ADMIN_BADGE_UPDATED',
  ADMIN_BADGE_DEACTIVATED: 'ADMIN_BADGE_DEACTIVATED',
  ADMIN_BADGE_AWARDED: 'ADMIN_BADGE_AWARDED',
  ADMIN_BADGE_REMOVED: 'ADMIN_BADGE_REMOVED',
  ADMIN_BADGE_DEFAULTS_INITIALIZED: 'ADMIN_BADGE_DEFAULTS_INITIALIZED',
  ADMIN_DAILY_CHALLENGE_RESET: 'ADMIN_DAILY_CHALLENGE_RESET',
} as const;

// SIgnificant changes have been made to the `AUDIT_ACTIONS` constant, which now includes a comprehensive list of audit action types categorized under various sections such as Authentication, User Management, Role Management, Data Operations, Claims Management, Policy Management, Payment Operations, System Operations, and Security Events. Each action type is represented as a string constant.

export type AuditActionType =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
